const fs = require('fs')
const path = require('path')
const express = require('express')
//const favicon = require('serve-favicon')
const compression = require('compression')
const resolve = file => path.resolve(__dirname, file)

const config = require('./config')

const isProduction = config.isProduction

const serverInfo =
	`express/${require('express/package.json').version} ` +
	`vue-server-renderer/${require('vue-server-renderer/package.json').version}`

const app = express()

let renderer
if (isProduction) {
	// In production: create server renderer using server bundle and index HTML
	// template from real fs.
	// The server bundle is generated by vue-ssr-webpack-plugin.
	const bundle = require('./_dist/vue-ssr-bundle.json')
	// src/index.template.html is processed by html-webpack-plugin to inject
	// build assets and output as dist/index.html.
	const template = fs.readFileSync(resolve('./_dist/index.html'), 'utf-8')
	renderer = createRenderer(bundle, template)
} else {
	// In development: setup the dev server with watch and hot-reload,
	// and create a new renderer on bundle / index template update.
	require('./build/setup-dev-server')(app, (bundle, template) => {
		renderer = createRenderer(bundle, template)
	})
}

function createRenderer (bundle, template) {
	// https://github.com/vuejs/vue/blob/dev/packages/vue-server-renderer/README.md#why-use-bundlerenderer
	return require('vue-server-renderer').createBundleRenderer(bundle, {
		template,
		cache: require('lru-cache')({
			max: 1000,
			maxAge: 1000 * 60 * 15
		})
	})
}

const serve = (path, cache) => express.static(resolve(path), {
	maxAge: cache && isProduction ? 60 * 60 * 24 * 30 : 0
})

app.use(compression({ threshold: 0 }))
//app.use(favicon('./static/logo.png'))
app.use('/dist', serve('./_dist', true))
app.use('/static', serve('./static', true))
app.use('/manifest.json', serve('./manifest.json', true))
app.use('/service-worker.js', serve('./_dist/service-worker.js'))

app.get('*', (req, res) => {
	if (!renderer) {
		return res.end('Waiting for compilation... Refresh in a moment.')
	}

	const s = Date.now()

	res.setHeader("Content-Type", "text/html")
	res.setHeader("Server", serverInfo)

	const errorHandler = err => {
		if (err && err.code === 404) {
			res.status(404).end('404 | Page Not Found')
		} else {
			// Render Error Page or Redirect
			res.status(500).end('500 | Internal Server Error')
			console.error(`Error during render : ${req.url}`)
			console.error(err)
		}
	}

	console.log(`Rendering: ${req.url}`)
	renderer.renderToStream({ url: req.url })
		.on('error', errorHandler)
		.on('end', () => console.log(`Whole request: ${Date.now() - s}ms`))
		.pipe(res)
})

const port = process.env.PORT || 8080
app.listen(port, () => {
	console.log(`Server started at localhost:${port}`)
})
